version: 1.0.0.{build}

pull_requests:
  do_not_increment_build_number: true

image: Ubuntu

services:
- docker

build:
  verbosity: minimal

build_script:
  - ./open-in-docker.sh specification/makeAllExts all
